### ISSUE TITLE
'openssl' on rubygems.org

### ISSUE THREAD

**Issue by rhenium** [mbailey/openssl#1]
Hi,

I'm one of the ext/openssl maintainers, and we are planning to convert ext/openssl into a "default gem" (a stdlib but can be upgraded via rubygems; rdoc is one example) in Ruby 2.4[1][2]. I'd like to include a gemified ext/openssl in Ruby 2.4.0-preview2, which is scheduled to be released on the next September[3].

So I have a request. Currently you have the 'openssl' namespace on rubygems.org, but would you mind giving it up?

Thanks,

[1] "Gemify OpenSSL" https://bugs.ruby-lang.org/issues/9612
[2] "Gemifying Ruby standard library" https://bugs.ruby-lang.org/issues/5481
[3] https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/ReleaseEngineering24

**Comment by mbailey** [comment]
Of course!

I only created it so I could report it as a security issue

**Comment by zzak** [comment]
We can also go directly through the RubyGems org to reclaim the gem.

**Comment by mbailey** [comment]
Sorry for the delay in responding. 

For the record I am totally happy with RubyGems.org taking this Gem from me.

Given the security implications, I would prefer RubyGems.org decide who to give OpenSSL to.

**Comment by rhenium** [comment]
Thank you!

According to https://github.com/rubygems/rubygems.org/issues/1155 (that's based on your report!), the name 'openssl' is protected at the moment.

**Comment by hsbt** [comment]
@mbailey Hi, I contacted with email for same issue. Sorry to my duplicated offer. 

Can you add @rhenium and me (hsbt at ruby-lang.org) to openssl owners? If you can not it, Please notify me.

**Comment by mbailey** [comment]
I am happy to have openssl taken from me but feel it would be irresponsible for me to decide who gets it.

rubygems.org has [blacklisted registration of gems that share a name with core libs](https://github.com/rubygems/rubygems.org/issues/1155).

I imagine rubygems.org probably have the context to decide who (if anyone) should control the openssl rubygem.

Do you know anyone at rubygems.org you could ask? Perhaps @arthurnn @dwradcliffe @sferik @indirect or [someone else from this thread](https://github.com/rubygems/rubygems.org/issues/1155)?

**Comment by dwradcliffe** [comment]
@hsbt has been handling the other stdlib gem migrations. See https://github.com/rubygems/rubygems.org/pull/1221 for an example. So I approve of adding him as an owner. Thanks! (And thanks for being careful!)

**Comment by mbailey** [comment]
@dwradcliffe 

Do you know anyone (besides me) with permission to transfer ownership? (of https://rubygems.org/gems/openssl)

I don't want to be obstructive but do not have the time to do due diligence required before transferring to ta third party. I can delete the gem if that's preferable.

**Comment by hsbt** [comment]
@mbailey Could you invoke following command?

```
$ gem owner openssl --add hsbt@ruby-lang.org
```

**Comment by mbailey** [comment]
Seriously guys, you've not acknowledged my concerns.

I do not want to be the guy who decides who gets the openssl rubygem. I registered it to test and report a security issue with Rubygems. 

<img width="609" alt="screen shot 2016-07-11 at 8 12 03 pm" src="https://cloud.githubusercontent.com/assets/4409/16727299/d1e8c548-47a3-11e6-9eaa-69c3655f990f.png">

To their credit the maintainers responded by [fixing the loophole](https://github.com/rubygems/rubygems.org/issues/1155) that allowed any old schmuck to register a gem that shared the name of a core library.

I don't know any of you personally. I cannot verify the authenticity of your comments.

Do you understand where I'm coming from?

**Comment by hsbt** [comment]
I understand your situation. but rubygems can not allow to delete gem. you can only yanked or added  owner grant to next maintainer.

If you can add owner grant to me, I remove to blacklist protection for stdlib of ruby core and override to our openssl extension. but you can not modify owner grant caused by blacklist protection of rubygems, you need to request to rubygems admins for db operation.

/cc @dwradcliffe

**Comment by dwradcliffe** [comment]
@mbailey Can you send a quick message with your intentions on http://help.rubygems.org/ and we can sort it out from there.

**Comment by mbailey** [comment]
@dwradcliffe Done https://github.com/rubygems/rubygems/issues/1663
